### ISSUE TITLE
Let the package be installed through CRAN

### ISSUE THREAD

**Issue by pacmandoh** [wjschne/arrowheadr#1]
Hi, @wjschne , Thanks for your excellent R pkg ❤️ !
Have you considered publishing `arrowheadr` to CRAN? In China, it is very troublesome to install the R package from github because of the network. I want to use `arrowheadr` as a dependency for my R package. It will be troublesome to install it from github.

**Comment by wjschne** [comment]
Yes, coincidentally, I submitted it to CRAN a few days ago. I am waiting to see if the latest submission is approved.

**Comment by wjschne** [comment]
It is now on CRAN:
https://cran.r-project.org/package=arrowheadr

**Comment by pacmandoh** [comment]
> It is now on CRAN: https://cran.r-project.org/package=arrowheadr

Thank you very much 🙏!
